# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "NEDERBURG"
license = "GPL-2"
licenselink = "https://github.com/appernetic/hugo-nederburg-theme/blob/master/LICENSE"
description = "Port of Tracks Theme https://www.competethemes.com/tracks/"
homepage = "https://github.com/appernetic/hugo-nederburg-theme"
tags = ["projects", "minimal", "responsive", "blog"]
features = ["disqus", "gravatar", "responsive", "google analytics"]
min_version = 0.34

[author]
  name = "GÃ¶ran Svensson"
  homepage = "https://github.com/appernetic"

# If porting an existing theme
[original]
  name = "tracks"
  homepage = "https://www.competethemes.com/tracks/"
