apiVersion: apps/v1
kind: Deployment
metadata:
  name: section-enged-deployment
  labels:
    app: section-enged
spec:
  replicas: 1
  selector:
    matchLabels:
      app: section-enged
  template:
    metadata:
      labels:
        app: section-enged
    spec:
      containers:
        - name: section-enged
          image: hborrelli12/section-enged:9c2d9
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /engineering-education/
              port: 80
            periodSeconds: 5
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /engineering-education/
              port: 80
            periodSeconds: 10
            initialDelaySeconds: 60
